### ISSUE TITLE
Directly return vector<string> where appropriate

### ISSUE THREAD

**Issue by jrk** [imageworks/pystring#12]
Is there a strong reason why the current API shies away from ever returning a vector of strings as a direct return value, like the actual Python API?

This is particularly useful with C++11 implementations, where `auto segs = split(s, delim)` is much more concise than having to make a separate and fully-qualified declaration for the `std::vector<std::string> segs` object before passing it as a mutable reference. In my understanding, modern compilers have no trouble optimizing away this pattern into an equivalent in-place mutation of the return object.

**Comment by brenthuisman** [comment]
I would like to thank the original authors and @clhsieh for his pull request. It works beautifully as a drop-in replacement for similar function I puzzled together.

**Comment by wolfv** [comment]
this is quite late, but I put together a fork of pystring which includes this change (actually returning a `std::vector<string_view>` where appropriate, and thus minimizes the amount of copies.
Also takes `string_view` as argument in many places (or template strings).

It's here for interested people: https://github.com/wolfv/pystring14

Note: I am happy to work with the original authors to incorporate any changes into a potential pystring v2 if desired!

**Comment by grdanny** [comment]
took us a bit of time. :-) 
but this now merged, thanks!!!
