### ISSUE TITLE
[SOLVED] pystring::split misunderstanding

### ISSUE THREAD

**Issue by ghost** [imageworks/pystring#13]
My little app crashes with segfault, here's Valgrind diagnosis (after using pystring::split in code):

<pre>6,253 bytes in 117 blocks are possibly lost in loss record 13 of 14
  in pystring::(anonymous namespace)::split_whitespace(std::string const&amp;, std::vector&lt;std::string, std::allocator&lt;std::string&gt; &gt;&amp;, int) in pystring/pystring.cpp:109
  1: operator new(unsigned long) in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so
  2: std::string::_Rep::_S_create(unsigned long, unsigned long, std::allocator&lt;char&gt; const&amp;) in /usr/lib/libstdc++.so.6.0.18
  3: char* std::string::_S_construct&lt;char*&gt;(char*, char*, std::allocator&lt;char&gt; const&amp;, std::forward_iterator_tag) in /usr/lib/libstdc++.so.6.0.18
  4: std::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;::basic_string(std::string const&amp;, unsigned long, unsigned long) in /usr/lib/libstdc++.so.6.0.18
  5: std::string::substr(unsigned long, unsigned long) const in /usr/lib/libstdc++.so.6.0.18
  6: pystring::(anonymous namespace)::split_whitespace(std::string const&amp;, std::vector&lt;std::string, std::allocator&lt;std::string&gt; &gt;&amp;, int) in <a href="file:///home/constantine/Scripts/build-Analyser-Desktop-Debug/../Analyser/pystring/pystring.cpp:109" >pystring/pystring.cpp:109</a>
  7: pystring::split(std::string const&amp;, std::vector&lt;std::string, std::allocator&lt;std::string&gt; &gt;&amp;, std::string const&amp;, int) in <a href="file:///home/constantine/Scripts/build-Analyser-Desktop-Debug/../Analyser/pystring/pystring.cpp:172" >pystring/pystring.cpp:172</a>
  8: ProcessLine(std::string const&amp;, datastorage&amp;) in <a href="file:///home/constantine/Scripts/build-Analyser-Desktop-Debug/../Analyser/main.cpp:54" >main.cpp:54</a>
  9: ProcessFile(char const*) in <a href="file:///home/constantine/Scripts/build-Analyser-Desktop-Debug/../Analyser/main.cpp:41" >main.cpp:41</a>
  10: main in <a href="file:///home/constantine/Scripts/build-Analyser-Desktop-Debug/../Analyser/main.cpp:28" >main.cpp:28</a></pre>

**Comment by lgritz** [comment]
Closing, solved long ago.
