### ISSUE TITLE
Deadlock in split_path

### ISSUE THREAD

**Issue by vjjjv** [imageworks/pystring#20]
This line deadlocks if path has double slash, like in "D:/dir//"

https://github.com/imageworks/pystring/blob/c2de99deb4f0bd13751f8436400b5e8662301769/pystring.cpp#L1364

I think the fix is to slice head2, not head:
`head2 = pystring::slice(head2,0,-1);`

**Comment by lgritz** [comment]
I'm embarrassed to say that this project has not had any reported bugs or patches offered for 5+ years (that's a strength, right?), and now nobody who had previously contributed to this project is still at SPI. We use it a lot, but so thoroughly take for granted its stability that there's nobody specifically assigned to it, nor easily identified as knowing about the internals. So our mechanism for dealing with reported problems is rusty, to say the least.

I think the best thing I can suggest is to ask you to please offer your proposed fix as a PR -- including a modification to test.cpp to specifically test this case and confirm the breakage before and the fix with this patch. If that looks good and passes the test, I will merge the code and tag a release.

**Comment by grdanny** [comment]
Your proposed fix looks good.
Looks like it was a typo or something.
I added a test case to test this on both windows and linux and merged it in pull request #24.

Thanks for spotting this!
