### ISSUE TITLE
Tests for abspath don't pass on Windows

### ISSUE THREAD

**Issue by wrosecrans** [imageworks/pystring#21]
This isn't really a show stopper, but on Windows the tests don't agree with the behavior, so the abspath tests fail.  The actual functionality seems sane and intentional, so I dunno if the fix is to change the behavior of the implementation to be consistent across platforms, or probably just change the expectation of the tests on Windows (or skip the abspath tests on Windows entirely).

Anyhow, here's what it is doing:
In test.cpp:
`PYSTRING_CHECK_EQUAL(pystring::os::path::abspath("", "/net"), "/net");`

But on windows the implementation uses "\" in canonical names rather than "/", because Windows.  So it fails because "\net" isn't equal to "/net"
The implementation of abspath on Windows runs `return normpath_nt(p);` to convert the '/' to '\' here
https://github.com/wrosecrans/pystring/blob/build/pystring.cpp#L1456

Here is a snippet of the output from running the tests:

Test [pystring] [translate] - PASSED
   D:\a\1\s\test.cpp:516:
  FAILED: pystring::os::path::abspath("", "/net") == "/net"
  	values were '\net' and '/net'
   D:\a\1\s\test.cpp:517:
   FAILED: pystring::os::path::abspath("../jeremys", "/net/soft_scratch/users/stevel") == "/net/soft_scratch/users/jeremys"
   	values were '\net\soft_scratch\users\jeremys' and '/net/soft_scratch/users/jeremys'
   D:\a\1\s\test.cpp:518:
   FAILED: pystring::os::path::abspath("../../../../tmp/a", "/net/soft_scratch/users/stevel") == "/tmp/a"
   	values were '\tmp\a' and '/tmp/a'
Test [pystring] [abspath] - FAILED
Test [pystring_os_path] [splitdrive] - PASSED
Test [pystring_os_path] [isabs] - PASSED

In the context of doing CI for a thing that uses PyString, it's convenient to be able to use the tests as a sanity check to make sure I haven't screwed up something completely in my build setup.  I am using CMake to build with the MSVC compiler instead of the Makefile that uses G++, but it's not doing anything particularly exciting:

https://github.com/wrosecrans/pystring/blob/build/CMakeLists.txt

**Comment by lgritz** [comment]
I'm embarrassed to say that this project has not had any reported bugs or patches offered for 5+ years (that's a strength, right?), and now nobody who had previously contributed to this project is still at SPI. We use it a lot, but so thoroughly take for granted its stability that there's nobody specifically assigned to it, nor easily identified as knowing about the internals. So our mechanism for dealing with reported problems is rusty, to say the least.

If you have a proposed fix, please do submit a PR -- including an appropriate test in test.cpp if this case is not already covered -- and I will merge the patch and tag a release.

**Comment by wrosecrans** [comment]
Haha, no worries.  I understand.  (I only hope I ever write something that nobody runs into a bug after five years of use.  For some reason, my own projects always seem to retain very recent organisational memory about such things!)

If I make a PR, would I need to sort out a CLA?

Would you take a PR that adds a CMakeLists.txt for building on non-gcc?

**Comment by lgritz** [comment]
Yes, sorry, CLAs are necessary to merge any code. It's practically the only constraint placed on our open source projects by the corporate overlords, so we feel obligated to be strict with that rule.

Yes, a CMake build system would be welcome. Somebody else also pointed out that the whole thing needs a generous sprinkling of 'const' if we really want to be modern and helpful.

We do continue to use pystring extensively internally, it's by no means abandoned... just that no change had been needed for so long that we kind of didn't notice that none of the original caretakers were still at the company. But I think we've identified somebody here who can continue to shepherd this project.

**Comment by wrosecrans** [comment]
Gotcha.  My employer is also pretty open source friendly, but there is a process for CLA review.  I submitted an internal request for approval, but it may be a little bit before that gets sorted out.  Sometimes the corporate wheels turn slowly.

And then I actually have to make time to sit down and write a PR.

**Comment by grdanny** [comment]
This has been addressed in PR #23 
I tested it on our end on both windows and linux, so it should be fine, but do let me know if anything looks strange on your end.

Thanks!
