### ISSUE TITLE
dev-cpp/pystring don't support gcc-10*

### ISSUE THREAD

**Issue by brothermechanic** [imageworks/pystring#28]
Hello
I have build issue
http://dpaste.com/5CCL3ENUA
Can you help me?

**Comment by grdanny** [comment]
Hello,

The link you included doesn't seem to have any info in it.
Can you paste the errors you are getting into the ticket?

Thanks!

**Comment by brothermechanic** [comment]
Oh, sorry
THis is a new paste http://dpaste.com/5HTJTFMMR

**Comment by grdanny** [comment]
Thanks for the updated paste.
Are you using some kind of package manager or CI there?

I don't see anything in the paste that indicates an error.
Is there maybe a more verbose log? Something that includes the compilation step?

This is what I'm seeing in the paste right now:


```
39;49;00mPackage:    dev-cpp/pystring-1.1.3
39;49;00mRepository: cg
39;49;00mUSE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
39;49;00mFEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
 Unpacking source...
 Unpacking pystring-1.1.3.tar.gz to /var/tmp/portage/dev-cpp/pystring-1.1.3/work
 Source unpacked in /var/tmp/portage/dev-cpp/pystring-1.1.3/work
 Preparing source in /var/tmp/portage/dev-cpp/pystring-1.1.3/work/pystring-1.1.3 ...
 Source prepared.
 Configuring source in /var/tmp/portage/dev-cpp/pystring-1.1.3/work/pystring-1.1.3 ...
 Source configured.
```

**Comment by brothermechanic** [comment]
this is source based gentoo linux
with portage (on python)
this is script for building packages
https://github.com/brothermechanic/cg/blob/master/dev-cpp/pystring/pystring-1.1.3.ebuild

This is global info of my OS
http://dpaste.com/EH2UW7HDV

**Comment by grdanny** [comment]
Hi There,

I got my hands on a gentoo box to do some testing. I have gcc 10 there.
I do have to admit I'm not so knowledgeable in ebuild though...

As a quick test can you just run:

`g++ --version
`
for example this is what I get:

```
 $ g++ --version
g++ (Gentoo 10.2.0-r5 p6) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

And then run:
```
 cd $HOME
 mkdir test_pystring_repo
 cd test_pystring_repo/
 git clone https://github.com/imageworks/pystring.git .
 make test
```

Which should run the unit tests and return something like:
```
 $ make test
rm -f -fr test
g++ pystring.cpp test.cpp -g -O3 -Wall -Wextra -Wshadow -Wconversion -Wcast-qual -Wformat=2 -DPYSTRING_UNITTEST=1 -o test
./test

PyStringUnitTests

Test [pystring] [endswith] - PASSED
Test [pystring] [find] - PASSED
Test [pystring] [rfind] - PASSED
Test [pystring] [replace] - PASSED
Test [pystring] [slice] - PASSED
Test [pystring] [split] - PASSED
Test [pystring] [rsplit] - PASSED
Test [pystring] [startswith] - PASSED
Test [pystring] [strip] - PASSED
Test [pystring] [translate] - PASSED
Test [pystring] [abspath] - PASSED
Test [pystring_os_path] [splitdrive] - PASSED
Test [pystring_os_path] [isabs] - PASSED
Test [pystring_os_path] [join] - PASSED
Test [pystring_os_path] [normpath] - PASSED
Test [pystring_os_path] [split] - PASSED
Test [pystring_os_path] [splitext] - PASSED

0 tests failed
```

If all this works then in theory your machine should be able to compile and run this in which case we need to focus on ebuild (if you have some tips for me on ebuild and how to test that .ebuild file that would help).
If it doesn't work and you get some error then please paste it and we can take it from there.

Thanks!

**Comment by grdanny** [comment]
Hi There, 

So looked at it some more over the weekend.
It seems like what is happening here is that there is a problem with the version of libtool that gentoo ships with.

You can download and compile your own version of libtool and that solves the issue on my end.

A better description of the problem and the solution is here:

http://www.metastatic.org/text/libtool.html

I ended up going with the solution outlined at the end, the part that start with "Another solution to this..."

So on my end I ended up running

```
mkdir local_libtool
cd local_libtool
 wget https://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.gz
tar xvf libtool-2.4.6.tar.gz
cd libtool-2.4.6
./configure
make
```

This gave me a freshly made libtool under $HOME/local_libtool/libtool-2.4.6/libtool

And then I swapped out the first line of the make file to point to this new libtool and everything works.

Let us know how it's going.

Thanks!

**Comment by brausepulver** [comment]
Hello,

thank you for taking the time to look into the problem. Although this is more related to Gentoo than pystring, I seem to have fixed the issue for me by installing libtool-9999 over libtool-2.4.6-r6.

**Comment by brothermechanic** [comment]
> Hi There,
> 
> So looked at it some more over the weekend.
> It seems like what is happening here is that there is a problem with the version of libtool that gentoo ships with.
> 
> You can download and compile your own version of libtool and that solves the issue on my end.
> 
> A better description of the problem and the solution is here:
> 
> http://www.metastatic.org/text/libtool.html
> 
> I ended up going with the solution outlined at the end, the part that start with "Another solution to this..."
> 
> So on my end I ended up running
> 
> ```
> mkdir local_libtool
> cd local_libtool
>  wget https://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.gz
> tar xvf libtool-2.4.6.tar.gz
> cd libtool-2.4.6
> ./configure
> make
> ```
> 
> This gave me a freshly made libtool under $HOME/local_libtool/libtool-2.4.6/libtool
> 
> And then I swapped out the first line of the make file to point to this new libtool and everything works.
> 
> Let us know how it's going.
> 
> Thanks!

THANK YOU VERY MUCH!!!
I reinstall libtool-2.4.6-r6::gentoo (just reinstall same version) and problem with pystring gone!!!
Super!
