### ISSUE TITLE
License is not "detected" as BSD-3 Clause by github

### ISSUE THREAD

**Issue by dfelinto** [imageworks/pystring#32]
Hi,

The license of this project seems to match the overall license of OpenColorIO (the only difference is that it mentions "Sony" directly, instead of referring only to the copyright holders.

It would help to have it explicitly detected as [BSD 3-Clause "New" or "Revised" License] by github.

---------------

More context, I'm updating Blender's 3rd party license document for Blender 3.2. We now depend on Pystrings since OCIO itselfs depends on it during build time.

It helps a lot to quickly find what is the license of a dependency without having to compare the license line-by-line to see if it is compatible with GPL :)

**Comment by lgritz** [comment]
Yes, that's reasonable, I'll work on the logistics of getting this change approved.
