### ISSUE TITLE
C++ version target?

### ISSUE THREAD

**Issue by peter-jansson** [imageworks/pystring#35]
With what lowest version of the C++ standard is pystring expected to work?

**Comment by grdanny** [comment]
Hello There,

Sorry for the late reply, we build and test against the following CXX_STANDARD 

        cxx_standard: [98, 11, 14, 17, 20]

So it's expected to work for those.

**Comment by peter-jansson** [comment]
Thank you, good to know before suggesting more fancy features from later standards.

**Comment by lgritz** [comment]
@peter-jansson Please do tell us about the fancy features.

I think we should absolutely bump the minimum to C++11 (if not 14) if there are any advantages to doing so. Beyond 14 is not a good idea, there's still too many environments used in VFX that are not ready for 17 compliance.

**Comment by peter-jansson** [comment]
For example, using [`auto`](https://en.cppreference.com/w/cpp/language/auto) when writing new code would be ok if C++11 was ok.
