### ISSUE TITLE
Which is the recommended stable release or commit?

### ISSUE THREAD

**Issue by joseangeljimenez** [imageworks/pystring#38]
Last release tag in this repository is v1.1.3 (Oct 17, 2012), however there are more recent commits.
Which one do you recommended? The 1.1.3 tagged release or cloning the latest commit?
Thank you!

**Comment by grdanny** [comment]
Good question, we are due for a new tag. 
Internally we use it from the tip of the repo. 
There weren't a ton of updates since 1.1.3, but there are some build system improvements and a few small fixes and performance improvements.

**Comment by grdanny** [comment]
I added a new tag:
https://github.com/imageworks/pystring/releases/tag/v.1.1.4
Thanks for the reminder!
