### ISSUE TITLE
Inconsistent tags. Breaks machinery

### ISSUE THREAD

**Issue by egorpugin** [imageworks/pystring#39]
![image](https://user-images.githubusercontent.com/4325333/207148934-86210663-eda8-4cf7-aca4-833922d56083.png)

**Comment by grdanny** [comment]
thanks for the heads up

**Comment by grdanny** [comment]
Should be fixed now. 
Let me know how it's going. Thanks for pointing that out
https://github.com/imageworks/pystring/tags

**Comment by egorpugin** [comment]
Works good, thank you.
