### ISSUE TITLE
Consider supporting std::wstring

### ISSUE THREAD

**Issue by vmtest888** [imageworks/pystring#40]
Consider supporting std::wstring

**Comment by xiaozhu1337** [comment]
Supporting wstring is really useful, although I like pystring, I had to switch to poco for this.

**Comment by xiaozhu1337** [comment]
The code of this project can be used as a reference
https://github.com/liwengithub/WinLib/blob/main/include/WinLibStr.h

**Comment by vmtest888** [comment]
> The code of this project can be used as a reference https://github.com/liwengithub/WinLib/blob/main/include/WinLibStr.h

老哥。你这个是真爱。哈哈哈。
