### ISSUE TITLE
Need python bindings

### ISSUE THREAD

**Issue by jeremyselan** [imageworks/pystring#8]
Sure, the python string functions are awesome if you need them in C++, but what is one to do if you need them in python?  Perhaps boost python would be appropriate?  (Please ping the developers before attempting this task, though). ;)

**Comment by xylcbd** [comment]
Funny. :)

**Comment by QiJune** [comment]
Funny. :)

**Comment by lgritz** [comment]
Old joke, not pending issue. Closing.
